%{
e = 50;
save('etf','e');
save('etnf','e');
save('ext','e');
save('ext2','e');
%}
script(1,1000,15,40,true);
load threshold;
script(1,1000,threshold,40,false);
load boosted;
load training;
load threshold;
save('cascades\1cascade','boosted_classifier','weak_classifiers','threshold');
script(2,2000,threshold,30,true);
load threshold;
script(2,2000,threshold,30,false);
load boosted;
load training;
load threshold;
save('cascades\2cascade','boosted_classifier','weak_classifiers','threshold');
script(3,3000,threshold,20,true);
load threshold;
script(3,3000,threshold,20,false);
load boosted;
load training;
load threshold;
save('cascades\3cascade','boosted_classifier','weak_classifiers','threshold');
script(4,4000,threshold,10,true);
load threshold;
script(4,4000,threshold,10,false);
load boosted;
load training;
load threshold;
save('cascades\4cascade','boosted_classifier','weak_classifiers','threshold');
script(5,5000,threshold,5,true);
load threshold;
script(5,5000,threshold,5,false);
load boosted;
load training;
load threshold;
save('cascades\5cascade','boosted_classifier','weak_classifiers','threshold');
train_ext2;
train_ext;